/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScoresRouteImport } from './routes/_app.scores'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMyResultsRouteImport } from './routes/_app.my-results'
import { Route as AppMyProfileRouteImport } from './routes/_app.my-profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as ApiPublicSeedAdminRouteImport } from './routes/api/public/seed-admin'
import { Route as AppReportCardStudentIdRouteImport } from './routes/_app.report-card.$studentId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScoresRoute = AppScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMyResultsRoute = AppMyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => AppRoute,
} as any)
const AppMyProfileRoute = AppMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSeedAdminRoute = ApiPublicSeedAdminRouteImport.update({
  id: '/api/public/seed-admin',
  path: '/api/public/seed-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportCardStudentIdRoute = AppReportCardStudentIdRouteImport.update({
  id: '/report-card/$studentId',
  path: '/report-card/$studentId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/my-results': typeof AppMyResultsRoute
  '/notifications': typeof AppNotificationsRoute
  '/results': typeof AppResultsRoute
  '/scores': typeof AppScoresRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
  '/report-card/$studentId': typeof AppReportCardStudentIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/my-profile': typeof AppMyProfileRoute
  '/my-results': typeof AppMyResultsRoute
  '/notifications': typeof AppNotificationsRoute
  '/results': typeof AppResultsRoute
  '/scores': typeof AppScoresRoute
  '/settings': typeof AppSettingsRoute
  '/students': typeof AppStudentsRoute
  '/subjects': typeof AppSubjectsRoute
  '/teachers': typeof AppTeachersRoute
  '/report-card/$studentId': typeof AppReportCardStudentIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/my-profile': typeof AppMyProfileRoute
  '/_app/my-results': typeof AppMyResultsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/scores': typeof AppScoresRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/report-card/$studentId': typeof AppReportCardStudentIdRoute
  '/api/public/seed-admin': typeof ApiPublicSeedAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classes'
    | '/dashboard'
    | '/my-profile'
    | '/my-results'
    | '/notifications'
    | '/results'
    | '/scores'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/report-card/$studentId'
    | '/api/public/seed-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classes'
    | '/dashboard'
    | '/my-profile'
    | '/my-results'
    | '/notifications'
    | '/results'
    | '/scores'
    | '/settings'
    | '/students'
    | '/subjects'
    | '/teachers'
    | '/report-card/$studentId'
    | '/api/public/seed-admin'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/my-profile'
    | '/_app/my-results'
    | '/_app/notifications'
    | '/_app/results'
    | '/_app/scores'
    | '/_app/settings'
    | '/_app/students'
    | '/_app/subjects'
    | '/_app/teachers'
    | '/_app/report-card/$studentId'
    | '/api/public/seed-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSeedAdminRoute: typeof ApiPublicSeedAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scores': {
      id: '/_app/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof AppScoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-results': {
      id: '/_app/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof AppMyResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-profile': {
      id: '/_app/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof AppMyProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/seed-admin': {
      id: '/api/public/seed-admin'
      path: '/api/public/seed-admin'
      fullPath: '/api/public/seed-admin'
      preLoaderRoute: typeof ApiPublicSeedAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report-card/$studentId': {
      id: '/_app/report-card/$studentId'
      path: '/report-card/$studentId'
      fullPath: '/report-card/$studentId'
      preLoaderRoute: typeof AppReportCardStudentIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMyProfileRoute: typeof AppMyProfileRoute
  AppMyResultsRoute: typeof AppMyResultsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppResultsRoute: typeof AppResultsRoute
  AppScoresRoute: typeof AppScoresRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppReportCardStudentIdRoute: typeof AppReportCardStudentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMyProfileRoute: AppMyProfileRoute,
  AppMyResultsRoute: AppMyResultsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppResultsRoute: AppResultsRoute,
  AppScoresRoute: AppScoresRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppReportCardStudentIdRoute: AppReportCardStudentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSeedAdminRoute: ApiPublicSeedAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
